name: Test
on: [push]
jobs:
  eslint:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci --legacy-peer-deps
      - name: Tests
        run: npm run test:run
